name: merge

on:
  push:
    branches: [main]

jobs:
  docker-build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker build and push
        uses: docker/build-push-action@v2
        with:
          file: docker/Dockerfile
          push: true
          tags: taikiinoue45/mvtec:base
